=== DANS-KNAW/easy-schema/src/main/assembly/dist/dcx/2017/09/dcx-dai.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2012 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dcx="http://easy.dans.knaw.nl/schemas/dcx/"
           xmlns:dcx-dai="http://easy.dans.knaw.nl/schemas/dcx/dai/"
           xmlns:dc="http://purl.org/dc/elements/1.1/"
           xmlns:datacite="http://datacite.org/schema/kernel-4"
           targetNamespace="http://easy.dans.knaw.nl/schemas/dcx/dai/"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <!-- =================================================================================== -->
    <xs:annotation>
        <xs:documentation xml:lang="en">Enabling the use of Digital Author ID (DAI).
            Structuring name and affiliation of dc:creator and dc:contributor.
        </xs:documentation>
    </xs:annotation>

    <!-- =================================================================================== -->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://easy.dans.knaw.nl/schemas/dcx/"
               schemaLocation="http://easy.dans.knaw.nl/schemas/dcx/2012/10/dcx.xsd"/>
    <xs:import namespace="http://purl.org/dc/elements/1.1/"
               schemaLocation="http://dublincore.org/schemas/xmls/qdc/dc.xsd"/>
    <xs:import namespace="http://datacite.org/schema/kernel-4"
               schemaLocation="http://schema.datacite.org/meta/kernel-4/metadata.xsd"/>

    <!-- =================================================================================== -->
    <xs:element name="creator" substitutionGroup="dc:creator" type="dcx-dai:DAIType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Extension of dc:creator.

                This element enables the use of the DAI attribute for specifying the Digital Author ID (DAI).
                If the name of an author can be split up into multiple fields or if an organization must be specified,
                the use of the element dcx-dai:creatorDetails is preferred.

                See also: http://purl.org/dc/elements/1.1/creator
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- =================================================================================== -->
    <xs:element name="contributor" substitutionGroup="dc:contributor" type="dcx-dai:DAIType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Extension of dc:contributor.

                This element enables the use of the DAI attribute for specifying the Digital Author ID (DAI).
                If the name of an author can be split up into multiple fields or if an organization must be specified,
                the use of the element dcx-dai:contributorDetails is preferred.

                See also: http://purl.org/dc/elements/1.1/contributor
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- =================================================================================== -->
    <xs:element name="creatorDetails" substitutionGroup="dc:creator" type="dcx-dai:AuthorOrOrganizationType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Extension of dc:creator.

                This element enables the detailed specification of a dcx-dai:author or dcx-dai:organization.

                See also: http://purl.org/dc/elements/1.1/creator
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- =================================================================================== -->
    <xs:element name="contributorDetails" substitutionGroup="dc:contributor" type="dcx-dai:AuthorOrOrganizationType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Extension of dc:contributor.

                This element enables the detailed specification of a dcx-dai:author or dcx-dai:organization.

                See also: http://purl.org/dc/elements/1.1/contributor
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <!-- =================================================================================== -->
    <xs:element name="author">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Detailed specification of a person that acts as a writer, creator or contributor.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:group ref="dcx-dai:AuthorInformationGroup"/>
        </xs:complexType>
    </xs:element>

    <!-- =================================================================================== -->
    <xs:complexType name="DAIType">
        <xs:complexContent>
            <xs:extension base="dc:SimpleLiteral">
                <xs:attribute name="DAI" type="dcx-dai:SimpleDaiType" use="required"/>
                <xs:attribute ref="xml:lang" use="prohibited"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- =================================================================================== -->
    <xs:simpleType name="SimpleDaiType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Digital Author ID (DAI) is composed of 8 or 9 digits and a MOD 11 checksum character.
                Use of a urified DAI (starting with info:eu-repo/dai/nl/) is allowed.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(info:eu-repo/dai/nl/){0,1}([0-9]{8,9})([0-9xX]{1})"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- =================================================================================== -->
    <xs:complexType name="AuthorOrOrganizationType">
        <xs:complexContent>
            <xs:extension base="dcx:ElementsOnlyNoLanguageAttributeType">
                <xs:choice>
                    <xs:element ref="dcx-dai:author"/>
                    <xs:element name="organization" type="dcx-dai:OrganizationalType"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- =================================================================================== -->
    <xs:complexType name="OrganizationalType">
        <xs:annotation>
            <xs:documentation xml:lang="en">Group of elements specifying information about an organization.</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="name" minOccurs="1" type="dcx-dai:LingualTokenType">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Designation or appalation of a company or institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="role" type="datacite:contributorType" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="AffiliationOrganizationalType">
        <xs:annotation>
            <xs:documentation xml:lang="en">Group of elements specifying information about an organization.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" minOccurs="1" type="dcx-dai:LingualTokenType">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Designation or appalation of a company or institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- =================================================================================== -->
    <xs:group name="AuthorInformationGroup">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Group of elements specifying information about an author.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="titles" type="dcx-dai:LingualTokenType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        (Academic) Title(s).
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="initials" type="xs:token" minOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Abbreviation of first names.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="insertions" type="xs:token" minOccurs="0">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Words between first name and last name, known as "tussenvoegsels" in Dutch.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="surname" type="xs:token" minOccurs="1">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Last name or family name.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="role" type="datacite:contributorType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Use one of the contributor types from datacite-v4</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="DAI" type="dcx-dai:SimpleDaiType" minOccurs="0">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Digital Author ID (DAI).
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="organization" type="dcx-dai:AffiliationOrganizationalType" minOccurs="0"/>
        </xs:all>
    </xs:group>

    <!-- =================================================================================== -->
    <xs:complexType name="LingualTokenType">
        <xs:simpleContent>
            <xs:extension base="xs:token">
                <xs:attribute ref="xml:lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- =================================================================================== -->

</xs:schema>

=== DANS-KNAW/easy-schema/src/main/assembly/dist/docs/examples/dcx-dai/example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    
    Copyright (C) 2012 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
    http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
    
-->

<dcx-dai:creatorDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dcx-dai="http://easy.dans.knaw.nl/schemas/dcx/dai/"
    xsi:schemaLocation="http://easy.dans.knaw.nl/schemas/dcx/dai/ ../../../dcx/2018/08/dcx-dai.xsd">
    <dcx-dai:author>
        <dcx-dai:titles xml:lang="en">B.L.I.S.</dcx-dai:titles>
        <dcx-dai:initials>J.P.H.</dcx-dai:initials>
        <dcx-dai:insertions>van den</dcx-dai:insertions>
        <dcx-dai:surname>Aarden</dcx-dai:surname>
        <dcx-dai:DAI>123456789</dcx-dai:DAI>
        <dcx-dai:role>RelatedPerson</dcx-dai:role>
        <dcx-dai:organization>
            <dcx-dai:name xml:lang="en">Maastricht University</dcx-dai:name>
            <dcx-dai:identifier scheme="ISNI" value="0000 0001 2103 2683" uri="http://isni.org/isni/0000000121032683"/>
        </dcx-dai:organization>
    </dcx-dai:author>
</dcx-dai:creatorDetails>
